### ISSUE TITLE
How to compute a classification report for a Part-of-Speech classifier ?

### ISSUE THREAD

**Issue by celsofranssa** [Cdiscount/IT-Blog#3]
Hello,

Is there an approach to measure the accuracy by TAG?

Thanks.

**Comment by cbornet** [comment]
Hi, for which blog are you asking your question ?

**Comment by celsofranssa** [comment]
Originally I read on:

 https://becominghuman.ai/part-of-speech-tagging-tutorial-with-the-keras-deep-learning-library-d7f93fa05537

But the above article make a pointer to:
https://techblog.cdiscount.com/

**Comment by cbornet** [comment]
cc @axelbellec

**Comment by axelbellec** [comment]
Hi @Ceceu,

Measuring model accuracy by tag is quite simple using the Scikit-Learn API.
You just have to predict on test set :   
```python
y_preds = clf.predict(X_test)
```
Then, `sklearn` provides an utility function to measure your [classifier performance by class](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html):
```python
from sklearn.metrics import classification_report

# Our target names are our label encoded targets
target_names = label_encoder.classes_
# Compute classification report
classif_report = classification_report(y_true=y_test, y_pred=y_preds, target_names=target_names)
print(classif_report)
```
This will return this report (actually, this is fake data):
```
              precision    recall  f1-score   support

           .       1.00      1.00      1.00        62
         ADJ       1.00      0.16      0.27        32
         ADP       0.70      0.90      0.79        52
         ADV       0.00      0.00      0.00        12
        CONJ       1.00      0.67      0.80        15
         DET       0.82      0.94      0.88        54
        NOUN       0.69      0.92      0.79       165
         NUM       1.00      0.11      0.20        27
        PRON       0.00      0.00      0.00         9
         PRT       1.00      0.68      0.81        19
        VERB       0.74      0.73      0.73        51
           X       0.83      1.00      0.91        25

   micro avg       0.77      0.77      0.77       523
   macro avg       0.73      0.59      0.60       523
weighted avg       0.78      0.77      0.73       523

```
__Note__: for the classification report, `y_true` (ground truth) must be a 1D array, so the label encoded `y_test` data, not the `y_test` made of dummies.

If you have any questions, please feel free to ask for clarification.

**Comment by celsofranssa** [comment]
Very good answer @axelbellec. But after put this code on evaluation part I have this output:
```
Traceback (most recent call last):
  File "/home/celso/projects/pos_tagger/pos_tagging_neural_nets_keras.py", line 217, in <module>
    classif_report = classification_report(y_true=y_test, y_pred=y_preds, target_names=target_names)
  File "/home/celso/anaconda3/envs/pos_tagger/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 1524, in classification_report
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/celso/anaconda3/envs/pos_tagger/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 81, in _check_targets
    "and {1} targets".format(type_true, type_pred))
ValueError: Classification metrics can't handle a mix of multilabel-indicator and multiclass targets
```

**Comment by axelbellec** [comment]
@Ceceu, can you share a minimal reproducible example consisting of the following items:
 - a minimal dataset, necessary to reproduce the error
 - the minimal runnable code necessary to reproduce the error, which can be run on the given dataset

Thanks

**Comment by celsofranssa** [comment]
@axelbellec, I am running the python file [pos_tagging_neural_nets_keras.py](https://github.com/Cdiscount/IT-Blog/blob/071c206e06292045c278c3c03dbbd4dec3d4226d/scripts/pos_tagging_neural_nets_keras.py#L205) from this repository.

I simply changed the lines (205 - 207) for the code snippet that you had shared in the previous answer:

This part of the code:
```python
    # Evaluate model accuracy
    score = clf.score(X_test, y_test, verbose=0)
    print('model accuracy: {}'.format(score))
```

... becomes:

```python
y_preds = clf.predict(X_test)
# Our target names are our label encoded targets
target_names = label_encoder.classes_
# Compute classification report
classif_report = classification_report(y_true=y_test, y_pred=y_preds, target_names=target_names)
print(classif_report)
```
Which can be seen in the edited [pos_tagging_neural_nets_keras.py](https://github.com/Ceceu/pos_tagger/blob/29962d35f9adc8f1664947db02240cb0ea49e9ec/pos_tagging_neural_nets_keras.py#L203).

I appreciate that you took your time to respond quickly. 
Thank you.

**Comment by axelbellec** [comment]
@Ceceu, as I told you before, `y_true` must be an 1D array so the label encoded target, not the one made of dummies (2D array). Your Keras neural network need dummies as input but `sklearn.metrics.classification_report` uses your label encoded target.

I have just updated my example by adding some suffix to `y` variables to distinguish encoded or dummy target variables.

_Updated script_ -> [`pos_tagging_neural_nets_keras.py`](https://github.com/Cdiscount/IT-Blog/blob/master/scripts/pos_tagging_neural_nets_keras.py#L171-L179)

**Comment by celsofranssa** [comment]
Thanks @axelbellec, worked perfectly. 
Sorry for the basic questions, I'm a beginner in NLP. 

If it is not an inconvenience, I have just one more question. I changed the corpus to `mac_morpho` as you can see in [pos_tagging_neural_nets_keras.py](https://github.com/Ceceu/pos_tagger/blob/9d79483e826d108d57fa29e514459b31550e84b1/pos_tagging_neural_nets_keras.py#L134).

The model is trained normally, but when evaluating even in the usual way (`score = clf.score(X_test_vect, y_test_dummy, verbose=0)`), I encounter the following error:

```python
Traceback (most recent call last):
  File "/home/celso/projects/pos_tagger/pos_tagging_neural_nets_keras.py", line 207, in <module>
    score = clf.score(X_test_vect, y_test_dummy, verbose=0)
  File "/home/celso/anaconda3/envs/pos_tagger/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py", line 294, in score
    outputs = self.model.evaluate(x, y, **kwargs)
  File "/home/celso/anaconda3/envs/pos_tagger/lib/python3.6/site-packages/keras/engine/training.py", line 1102, in evaluate
    batch_size=batch_size)
  File "/home/celso/anaconda3/envs/pos_tagger/lib/python3.6/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "/home/celso/anaconda3/envs/pos_tagger/lib/python3.6/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_3 to have shape (31,) but got array with shape (29,)
```
I tried to find the solution but I'm stuck on this problem. Thanks for any help.

Thank you very much.

**Comment by axelbellec** [comment]
Hello @Ceceu. 
I think that you need to increase the number of samples to test your model. 
You need to have the same number of classes in your train/valid/test datasets. 
This is why Keras outputs that the shape of your test vector (29,) does not match with the one used to train the model (31,).

**Comment by celsofranssa** [comment]
Great \o/
I fix it quickly.
Thank you for all the help you provided.
